services:
  caplog-api:
    image: 242777378795.dkr.ecr.ap-northeast-2.amazonaws.com/caplog-api:latest
    container_name: caplog-api
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      # 내부 도커 네트워크의 db 서비스(caplog-db)로 연결
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
    
      TOKEN_PUBLIC_KEY: ${TOKEN_PUBLIC_KEY}
      TOKEN_PRIVATE_KEY: ${TOKEN_PRIVATE_KEY}

      S3_BUCKET_NAME: ${S3_BUCKET_NAME}

    networks:
      - app-network



  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - caplog-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# 로컬 DB 데이터 보존용 볼륨 선언
volumes:
  mysql_data: