spring:
  application:
    name: caplog

  profiles:
    default: local # active 지정이 없을 때 기본적으로 local 프로필을 읽음

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  # AI 공통 설정
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    vectorstore:
      qdrant:
        host: ${QDRANT_HOST:localhost}
        port: ${QDRANT_PORT:6334}
        collection-name: user_groups
        initialize-schema: true